- name: Instal GEL
  hosts:
    - write
    - backend
    - read
  vars:
    gel_version: 1.7.0
    gel_url: https://reposilite.work.lan/releases/com/grafana/gel/1.7.0/enterprise-logs-v1.7.0-linux-amd64
    # https://dl.grafana.com/gel/releases/enterprise-logs-v{{ gel_version }}-linux-amd64
  tasks:

    - name: create the enterprise-logs user
      user:
        name: enterprise-logs
        create_home: yes
        shell: /bin/bash


    - name: create /etc/enterprise-logs directory
      file:
        path: /etc/enterprise-logs
        state: directory

    - name: create /etc/enterprise-logs/runtime-config/ directory
      file:
        path: /etc/enterprise-logs/runtime-config/
        state: directory

    - name: create /var/lib/enterprise-logs directory
      file:
        path: /var/lib/enterprise-logs
        state: directory
        owner: enterprise-logs
        group: enterprise-logs

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /root/downloads
        state: directory
        mode: '0755'
        
    - name: check if GEL is present
      stat:
        path: /root/downloads/enterprise-logs-v{{ gel_version }}-linux-amd64
      register: stat_gel

    - name: download GEL
      get_url:
        url: "{{ gel_url }}"
        dest: /root/downloads/enterprise-logs-v{{ gel_version }}-linux-amd64
        validate_certs: false
      when: not stat_gel.stat.exists

    - name: install GEL
      copy:
        remote_src: yes
        src: /root/downloads/enterprise-logs-v{{ gel_version }}-linux-amd64
        dest: /usr/local/bin/enterprise-logs
        mode: 0755


