
appconfig:
  # platform essentials on 172.18.0.x
  traefik: 
    ip: 172.18.0.2
    image: "{{ images['traefik'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      - "80:80"
      - "443:443"
      # - "8080:8080"

  portainer: 
    ip: 172.18.0.3
    image: "{{ images['portainer-ce'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  # artifact repositories 172.18.1.x
  registry: 
    ip: 172.18.1.2
    image: "{{ images['registry'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  regui: 
    ip: 172.18.1.3
    image: "{{ images['docker-registry-ui'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  reposilite: 
    ip: 172.18.1.4
    image: "{{ images['reposilite'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  # identity and access Management 172.18.2.x
  keycloak: 
    ip: 172.18.2.2
    image: "{{ images['keycloak'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  # databases 172.18.3.x
  oracledb: 
    ip: 172.18.3.2
    image: "{{ images['oracledb'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 54321
    exec_as_group: 54321
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      # - "1521:1521"

  mysql: 
    ip: 172.18.3.3
    image: "{{ images['mysql'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      # - "3305:3306"

  mariadb: 
    ip: 172.18.3.4 
    image: "{{ images['mariadb'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      # - "3306:3306"
      
  postgres: 
    ip: 172.18.3.5
    image: "{{ images['postgres'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      # - "5432:5432"

  adminer:
    ip: 172.18.3.6
    image: "{{ images['adminer'] }}"
    
    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
    
  # storage 172.18.4.x
  minio:
    ip: 172.18.4.2
    image: "{{ images['minio'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  # messaging 172.18.5.x
  zookeeper: 
    ip: 172.18.5.2
    image: "{{ images['kafka'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  kafka: 
    ip: 172.18.5.3
    image: "{{ images['kafka'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  kafdrop: 
    ip: 172.18.5.4
    image: "{{ images['kafdrop'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  kafkaexporter:
    ip: 172.18.5.5
    image: "{{ images['kafka'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  artemis: 
    ip: 172.18.5.6
    image: "{{ images['artemis'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      - 61616:61616

  # observability

  #only needed for 32 bits systems when grafana agent does not work.
  node-exporter: 
    image: "{{ images['node-exporter'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  promgcloud: 
    ip: 172.18.6.2
    image: "{{ images['prometheus'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  memcached:
    ip: 172.18.6.3
    image: "{{ images['memcached'] }}"
    
    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  cadvisor: 
    ip: 172.18.6.4
    image: "{{ images['cadvisor'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  prometheus: 
    ip: 172.18.6.5
    image: "{{ images['prometheus'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  gem: 
    ip: 172.18.6.6
    image: "{{ images['gem'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  gel: 
    ip: 172.18.6.7
    image: "{{ images['gel'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  get: 
    ip: 172.18.6.8
    image: "{{ images['get'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  grafana-enterprise: 
    ip: 172.18.6.9
    image: "{{ images['grafana-enterprise'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

    prom_url: http://mimir:8080/prometheus
    gem_app_url: https://reposilite.aphm.duckdns.org/releases/com/grafana/gem-app/4.0.6/grafana-metrics-enterprise-app-v4.0.6.zip
    gel_app_url: https://reposilite.aphm.duckdns.org/releases/com/grafana/gel-app/3.1.1/grafana-enterprise-logs-app-3.1.1.zip
    get_app_url: https://reposilite.aphm.duckdns.org/releases/com/grafana/get-app/2.1.1/grafana-enterprise-traces-app-2.1.1.zip

  grafana-alloy:
    ip: 172.18.6.10
    # image: "{{ images['agent'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports:
 
  otel-collector:
    ip: 172.18.6.12
    image: "{{ images['otel-collector'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  # functional applications are on network 172.18.100.X
  smoke-test-app:
    ip: 172.18.100.2
    image: "{{ images['smoke-test-app'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 