---
appconfig:
  plex: 
    image: "{{ images['plex'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
    
  rentman:
    ip: 172.18.1.20
    image: "{{ images['rentman'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  teddycast:
    ip: 172.18.1.21
    image: "{{ images['teddycast'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

  pkdex:
    ip: 172.18.1.22
    image: "{{ images['pkdex'] }}"

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 