# Last updated 2024-05-04

images:
  # Kube
  # sudo kubeadm config images list
  kube-apiserver: registry.k8s.io/kube-apiserver:v1.29.6
  kube-controller-manager: registry.k8s.io/kube-controller-manager:v1.29.6
  kube-scheduler: registry.k8s.io/kube-scheduler:v1.29.6
  kube-proxy: registry.k8s.io/kube-proxy:v1.29.6
  pause: registry.k8s.io/pause:3.9
  etcd: registry.k8s.io/etcd:3.5.12-0
  coredns: registry.k8s.io/coredns/coredns:v1.11.1

  # metrics server
  # https://github.com/kubernetes-sigs/metrics-server
  metrics-server: registry.k8s.io/metrics-server/metrics-server:v0.7.1
  
  # Flannel
  # https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  flannel-cni-plugin: flannel/flannel-cni-plugin:v1.4.1-flannel1
  flannel: flannel/flannel:v0.25.4

  # ingress nginx
  
  # original https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
  # https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
  controller: registry.k8s.io/ingress-nginx/controller:1.11.0
  kube-webhook-certgen: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.1

  # storage
  # https://github.com/rancher/local-path-provisioner
  local-path-provisioner: rancher/local-path-provisioner:v0.0.28

  # Minio
  # https://hub.docker.com/r/minio/minio/tags
  minio: minio/minio:RELEASE.2024-09-22T00-33-43Z

  # https://hub.docker.com/_/busybox/tags?page=1&name=1.
  busybox: docker.io/busybox:1.36.1
  curl: curlimages/curl:8.7.1

  # Grafana stack observability

  # Metrics
  # https://hub.docker.com/r/grafana/enterprise-metrics/tags?page=1&name=2.
  gem: grafana/enterprise-metrics:v2.13.1
  # https://hub.docker.com/r/grafana/mimir/tags?page=1&name=2.
  mimir: grafana/mimir:2.13.0
  # https://hub.docker.com/r/bitnami/memcached/tags?page=1&name=1.
  memcached: bitnami/memcached:1.6.31
  # https://hub.docker.com/r/bitnami/memcached-exporter/tags?page=1&name=0..
  memcached-exporter: bitnami/memcached-exporter:0.14.4
  # Logs
  # https://hub.docker.com/r/grafana/enterprise-logs/tags?page=1&name=3.
  gel: grafana/enterprise-logs:3.2.0
  # https://hub.docker.com/r/grafana/loki/tags?page=1&name=3.
  loki: grafana/loki:3.2.0
  # https://hub.docker.com/r/grafana/promtail/tags?page=1&name=3.
  promtail: grafana/promtail:3.2.0

  # Traces
  # https://hub.docker.com/r/grafana/enterprise-traces/tags?page=1&name=2.
  get: grafana/enterprise-traces:v2.5.0
  # https://hub.docker.com/r/grafana/tempo/tags?page=1&name=2.
  tempo: grafana/tempo:2.6.0

  # Grafana
  # https://hub.docker.com/r/grafana/grafana/tags?page=1&name=11.
  grafana: grafana/grafana:11.2.1
  grafana-enterprise: grafana/grafana-enterprise:11.2.1
  
  # https://hub.docker.com/r/grafana/alloy/tags?page=1&name=v1.
  alloy: grafana/alloy:v1.2.1
  # https://hub.docker.com/r/prom/prometheus/tags?page=1&name=2.
  prometheus: prom/prometheus:v2.53.1
  # https://hub.docker.com/r/prom/node-exporter/tags?page=1&name=1.
  node-exporter: prom/node-exporter:v1.8.1
  # https://hub.docker.com/r/prom/alertmanager/tags?page=1&name=0.
  alertmanager: prom/alertmanager:v0.27.0

  # https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags?page=&page_size=&ordering=&name=0.
  otel-collector: otel/opentelemetry-collector-contrib:0.104.0
  # https://hub.docker.com/r/bitnami/kubectl/tags?page=1&name=1.29
  kubectl: bitnami/kubectl:1.29.6

  # https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor
  cadvisor: gcr.io/cadvisor/cadvisor:v0.49.1
  # https://github.com/kubernetes/kube-state-metrics
  kube-state-metrics: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.12.0
  
  # Databases
  # https://hub.docker.com/_/mariadb
  mariadb: docker.io/mariadb:11.3.2
  # https://hub.docker.com/_/mysql/tags?page=1&name=8.
  mysql: docker.io/mysql:8.4.1
  # https://hub.docker.com/_/postgres
  postgres: docker.io/postgres:16.3
  # https://hub.docker.com/_/elasticsearch
  elasticsearch: docker.io/elasticsearch:8.14.3
  kibana: docker.io/kibana:8.14.3

  # oracledb: container-registry.oracle.com/database/free:23.3.0.0
  oracledb: oracledb:19.3.0
  # https://hub.docker.com/_/adminer/tags?page=1&name=4.
  adminer: docker.io/adminer:4.8.1

  # messaging
  # https://quay.io/repository/strimzi/kafka?tab=tags&tag=latest
  kafka: quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
  # https://hub.docker.com/r/obsidiandynamics/kafdrop/tags?page=1&name=4.
  kafdrop: obsidiandynamics/kafdrop:4.0.2
  # https://hub.docker.com/r/apache/activemq-artemis/tags?page=1&name=2.
  artemis: apache/activemq-artemis:2.35.0

  # platform essentials
  # https://hub.docker.com/r/portainer/portainer-ce/tags?page=1&name=2.
  portainer-ce: portainer/portainer-ce:2.21.2
  # https://hub.docker.com/_/registry/tags?page=1&name=2.
  registry: docker.io/registry:2.8.3 # docker.io/registry:2.8.2
  # https://hub.docker.com/r/joxit/docker-registry-ui/tags?page=1&name=2.
  docker-registry-ui: joxit/docker-registry-ui:2.5.7
  # https://hub.docker.com/_/traefik/tags?page=1&name=3.
  # https://github.com/traefik/traefik/releases 
  traefik: docker.io/traefik:3.1.4
  
  # https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags?page=&page_size=&ordering=&name=1.
  nginx: nginxinc/nginx-unprivileged:1.27.0
    
  # https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest
  keycloak: quay.io/keycloak/keycloak:25.0.1-0
  # https://hub.docker.com/r/dzikoysk/reposilite/tags?page=1&name=3.
  reposilite: dzikoysk/reposilite:3.5.14

  # Demo Applications
  smoke-test-app: alainpham/smoke-test-app:2.0.3

  # Misc
  # https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=17.
  eclipse-temurin: docker.io/eclipse-temurin:17.0.11_9-jre

  # Media server
  # https://hub.docker.com/r/linuxserver/plex/tags?page=1&name=1.
  plex: linuxserver/plex:1.40.2
  # https://hub.docker.com/r/linuxserver/jellyfin/tags?page=1&name=10.
  jellyfin: linuxserver/jellyfin:10.9.7
  teddycast: registry.awon.cpss.duckdns.org/teddycast:1.0.7
  rentman: registry.awon.cpss.duckdns.org/rentman:1.0.4
  pkdex: registry.awon.cpss.duckdns.org/pkdex:1.0.4

  wireguard: linuxserver/wireguard:1.0.20210914
  # https://hub.docker.com/r/linuxserver/transmission/tags
  transmission: linuxserver/transmission:4.0.6
  # https://hub.docker.com/r/linuxserver/radarr/tags
  radarr: linuxserver/radarr:5.4.6
  # https://hub.docker.com/r/linuxserver/bazarr/tags
  bazarr: linuxserver/bazarr:1.4.2
  # https://hub.docker.com/r/jc21/nginx-proxy-manager/tags?page=1&name=2.
  nginx-proxy-manager: jc21/nginx-proxy-manager:2.10.4
  # https://hub.docker.com/r/linuxserver/nextcloud/tags
  nextcloud: linuxserver/nextcloud:29.0.3

  # https://hub.docker.com/r/linuxserver/homeassistant/tags
  homeassistant: linuxserver/homeassistant:2024.7.2

  # https://hub.docker.com/r/linuxserver/netbootxyz/tags?page=&page_size=&ordering=&name=0.
  netbootxyz: linuxserver/netbootxyz:0.7.1

  # https://hub.docker.com/r/joseluisq/static-web-server/tags
  static: joseluisq/static-web-server:2.32.0

  # https://hub.docker.com/r/syncthing/syncthing/tags?page=&page_size=&ordering=&name=1.
  syncthing: syncthing/syncthing:1.27.10