# Last updated 2023-09-01

images:
  # Kube
  # sudo kubeadm config images list
  kube-apiserver: registry.k8s.io/kube-apiserver:v1.27.5
  kube-controller-manager: registry.k8s.io/kube-controller-manager:v1.27.5
  kube-scheduler: registry.k8s.io/kube-scheduler:v1.27.5
  kube-proxy: registry.k8s.io/kube-proxy:v1.27.5
  pause: registry.k8s.io/pause:3.9
  etcd: registry.k8s.io/etcd:3.5.7-0
  coredns: registry.k8s.io/coredns/coredns:v1.10.1

  # metrics server
  # https://github.com/kubernetes-sigs/metrics-server
  metrics-server: registry.k8s.io/metrics-server/metrics-server:v0.6.4
  
  # Flannel
  # https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  flannel-cni-plugin: flannel/flannel-cni-plugin:v1.2.0
  flannel: flannel/flannel:v0.22.1

  # ingress nginx
  
  # original https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
  # https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
  controller: registry.k8s.io/ingress-nginx/controller:v1.8.1
  kube-webhook-certgen: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407

  # kube ui

  # https://github.com/kubernetes/dashboard
  dashboard: kubernetesui/dashboard:v2.7.0
  # https://github.com/kubernetes-sigs/dashboard-metrics-scraper
  metrics-scraper: kubernetesui/metrics-scraper:v1.0.9

  # storage
  # https://github.com/rancher/local-path-provisioner
  local-path-provisioner: rancher/local-path-provisioner:v0.0.24

  # Minio
  # https://hub.docker.com/r/minio/minio/tags
  minio: minio/minio:RELEASE.2023-08-31T15-31-16Z

  # https://hub.docker.com/_/busybox/tags?page=1&name=1.
  busybox: docker.io/busybox:1.36.1
  curl: curlimages/curl:8.2.1

  # Grafana stack observability

  # Metrics
  # https://hub.docker.com/r/grafana/enterprise-metrics/tags?page=1&name=2.
  enterprise-metrics: grafana/enterprise-metrics:v2.9.0
  # https://hub.docker.com/r/grafana/mimir/tags?page=1&name=2.
  mimir: grafana/mimir:2.9.0
  # https://hub.docker.com/r/bitnami/memcached/tags?page=1&name=1.
  memcached: bitnami/memcached:1.6.21-debian-11-r58
  # https://hub.docker.com/r/bitnami/memcached-exporter/tags?page=1&name=0..
  memcached-exporter: bitnami/memcached-exporter:0.13.0-debian-11-r71
  # Logs
  # https://hub.docker.com/r/grafana/enterprise-logs/tags?page=1&name=1.
  enterprise-logs: grafana/enterprise-logs:v1.7.3
  # https://hub.docker.com/r/grafana/loki/tags?page=1&name=2.
  loki: grafana/loki:2.8.4
  # https://hub.docker.com/r/grafana/promtail/tags?page=1&name=2.
  promtail: grafana/promtail:2.8.4

  # Traces
  # https://hub.docker.com/r/grafana/enterprise-traces/tags?page=1&name=2.
  enterprise-traces: grafana/enterprise-traces:v2.1.0
  # https://hub.docker.com/r/grafana/tempo/tags?page=1&name=2.
  tempo: grafana/tempo:2.2.0

  # Grafana
  # https://hub.docker.com/r/grafana/grafana/tags?page=1&name=10.
  grafana: grafana/grafana:10.1.4
  grafana-enterprise: grafana/grafana-enterprise:10.1.4
  # https://hub.docker.com/r/grafana/grafana-oss-dev/tags?page=1&ordering=last_updated&name=10.1
  grafana-oss-dev: grafana/grafana-oss-dev:10.2.0-131062
  
  # https://hub.docker.com/r/grafana/agent/tags?page=1&name=0.
  agent: grafana/agent:v0.35.4  # latest is with faro enable v0.28.1

  # https://hub.docker.com/r/prom/prometheus/tags?page=1&name=2.
  prometheus: prom/prometheus:v2.46.0
  # https://hub.docker.com/r/prom/node-exporter/tags?page=1&name=1.
  node-exporter: prom/node-exporter:v1.6.1
  # https://hub.docker.com/r/prom/alertmanager/tags?page=1&name=0.
  alertmanager: prom/alertmanager:v0.25.0
  
  # https://hub.docker.com/r/bitnami/kubectl/tags?page=1&name=1.25
  kubectl: bitnami/kubectl:1.27.4

  # https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor
  cadvisor: gcr.io/cadvisor/cadvisor:v0.47.2
  # https://github.com/kubernetes/kube-state-metrics
  kube-state-metrics: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2
  
  # Databases
  # https://hub.docker.com/_/mariadb
  mariadb: docker.io/mariadb:11.0.3
  # https://hub.docker.com/_/mysql/tags?page=1&name=8.
  mysql: docker.io/mysql:8.0.34
  # https://hub.docker.com/_/postgres
  postgres: docker.io/postgres:15.4
  # https://hub.docker.com/_/elasticsearch
  elasticsearch: docker.io/elasticsearch:8.8.1
  kibana: docker.io/kibana:8.8.1

  oracledb: oracledb:19.3.0
  # https://hub.docker.com/_/adminer/tags?page=1&name=4.
  adminer: docker.io/adminer:4.8.1

  # messaging
  # https://quay.io/repository/strimzi/kafka?tab=tags&tag=latest
  kafka: quay.io/strimzi/kafka:0.36.1-kafka-3.4.1
  # https://hub.docker.com/r/obsidiandynamics/kafdrop/tags?page=1&name=3.
  kafdrop: obsidiandynamics/kafdrop:3.31.0
  # https://hub.docker.com/r/provectuslabs/kafka-ui/tags?page=1&name=0.
  kafka-ui: provectuslabs/kafka-ui:v0.7.1
  artemis: alainpham/artemis:2.28.0

  # platform essentials
  # https://hub.docker.com/r/portainer/portainer-ce/tags?page=1&name=2.
  portainer-ce: portainer/portainer-ce:2.19.1
  # https://hub.docker.com/_/registry/tags?page=1&name=2.
  registry: docker.io/registry:2.8.2 # docker.io/registry:2.8.2
  # https://hub.docker.com/r/joxit/docker-registry-ui/tags?page=1&name=2.
  docker-registry-ui: joxit/docker-registry-ui:2.5.2
  # https://hub.docker.com/_/traefik/tags?page=1&name=2.
  traefik: docker.io/traefik:2.10.4
  
  # https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags?page=1&name=1.
  nginx: nginxinc/nginx-unprivileged:1.24-alpine
  
  # https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest
  keycloak: quay.io/keycloak/keycloak:22.0.1-2
  # https://hub.docker.com/r/dzikoysk/reposilite/tags?page=1&name=3.
  reposilite: dzikoysk/reposilite:3.4.10

  # Demo Applications
  web-shop: alainpham/web-shop:1.8
  shopping-cart: alainpham/shopping-cart:1.3
  products: alainpham/products:otel-1.3
  smoke-test-app: alainpham/smoke-test-app:2.0.3
  serve: philippgille/serve:0.3.0

  # Misc
  # https://hub.docker.com/r/ubuntu/squid/tags?page=1&name=5.2
  squid: ubuntu/squid:5.2-22.04_beta
  # https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=17.
  eclipse-temurin: docker.io/eclipse-temurin:17.0.8.1_1-jre
  # https://hub.docker.com/r/sonatype/nexus3/tags?page=1&name=3.
  nexus3: sonatype/nexus3:3.59.0
