images:
  # Kube
  kube-apiserver: registry.k8s.io/kube-apiserver:v1.25.8
  kube-controller-manager: registry.k8s.io/kube-controller-manager:v1.25.8
  kube-scheduler: registry.k8s.io/kube-scheduler:v1.25.8
  kube-proxy: registry.k8s.io/kube-proxy:v1.25.8
  pause: registry.k8s.io/pause:3.8
  etcd: registry.k8s.io/etcd:3.5.6-0
  coredns: registry.k8s.io/coredns/coredns:v1.9.3

  # metrics server
  metrics-server: registry.k8s.io/metrics-server/metrics-server:v0.6.3

  # Flannel
  flannel-cni-plugin: flannel/flannel-cni-plugin:v1.1.2
  flannel: flannel/flannel:v0.21.4

  # ingress nginx
  controller: registry.k8s.io/ingress-nginx/controller:v1.7.0
  kube-webhook-certgen: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794

  # kube ui
  dashboard: kubernetesui/dashboard:v2.7.0
  metrics-scraper: kubernetesui/metrics-scraper:v1.0.8

  # storage
  local-path-provisioner: rancher/local-path-provisioner:v0.0.24

  # Minio
  minio: minio/minio:RELEASE.2023-04-13T03-08-07Z
  busybox: docker.io/busybox:1.36.0
  curl: curlimages/curl:8.00.1

  # Grafana stack observability

  # Metrics
  enterprise-metrics: grafana/enterprise-metrics:v2.7.0
  mimir: grafana/mimir:2.7.1
  memcached: docker.io/memcached:1.6.19-alpine
  memcached-exporter: prom/memcached-exporter:v0.11.2

  # Logs
  enterprise-logs: grafana/enterprise-logs:v1.6.2
  loki: grafana/loki:2.7.4
  promtail: grafana/promtail:2.7.4

  # Traces
  enterprise-traces: grafana/enterprise-traces:v1.3.0
  tempo: grafana/tempo:1.5.0

  # Grafana
  grafana: grafana/grafana:9.4.7
  grafana-enterprise: grafana/grafana-enterprise:9.4.7
  grafana-oss-dev: grafana/grafana-oss-dev:9.5.0-107484pre
   
  agent: grafana/agent:v0.28.1  # latest is grafana/agent:v0.31.2


  prometheus: prom/prometheus:v2.43.0
  node-exporter: prom/node-exporter:v1.5.0
  cadvisor: gcr.io/cadvisor/cadvisor:v0.47.1
  kube-state-metrics: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.0
  
  # Databases
  mariadb: docker.io/mariadb:10.11.2
  mysql: docker.io/mysql:8.0.32
  postgres: docker.io/postgres:15.2
  elasticsearch: docker.io/elasticsearch:8.6.2
  kibana: docker.io/kibana:8.6.2
  oracledb: oracledb:19.3.0

  adminer: docker.io/adminer:4.8.1

  # messaging
  kafka: quay.io/strimzi/kafka:0.34.0-kafka-3.4.0
  kafdrop: obsidiandynamics/kafdrop:3.31.0
  kafka-ui: provectuslabs/kafka-ui:v0.6.0
  artemis: alainpham/artemis:2.28.0

  # platform essentials
  portainer-ce: portainer/portainer-ce:2.17.1
  nexus3: sonatype/nexus3:3.50.0
  registry: docker.io/registry:2.8.1
  docker-registry-ui: joxit/docker-registry-ui:2.4.1
  traefik: docker.io/traefik:2.9.9
  keycloak: quay.io/keycloak/keycloak:21.0.2-0
  reposilite: dzikoysk/reposilite:3.4.0

  # Demo Applications
  web-shop: alainpham/web-shop:1.8
  shopping-cart: alainpham/shopping-cart:1.3
  products: alainpham/products:otel-1.3
  smoke-test-app: alainpham/smoke-test-app:1.2.1
  serve: philippgille/serve:0.3.0
  
  # Misc
  squid: ubuntu/squid:5.2-22.04_beta
  eclipse-temurin: docker.io/eclipse-temurin:11.0.18_10-jre
