---
- set_fact:
    appname: nginx-proxy-manager

- name: provision infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-provision


- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    hostname: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "{{ appconfig[appname].exec_as_user }}:{{ appconfig[appname].exec_as_group }}"
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"
    command: 
    env:
      PUID: "{{ appconfig[appname].exec_as_user }}"
      PGID: "{{ appconfig[appname].exec_as_group }}"
      DISABLE_IPV6: 'true'
    labels: |
      {
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/data"
      - "/home/{{ansible_user}}/apps/tls/cfg:/etc/letsencrypt"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if server is up
  when:  appconfig[appname].appstate == 'started'
  uri:
    url: "http://{{inventory_hostname}}"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2

- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete