---
- set_fact:
    appname: jellyfin

- name: provision infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-provision

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"
    env:
      PUID: "{{ appconfig[appname].exec_as_user }}"
      PGID: "{{ appconfig[appname].exec_as_group }}"
      TZ: "Europe/Paris"
    labels: |
      {
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "8096",
        "traefik.http.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.routers.{{appname}}.rule": "Host(`{{appname}}.{{inventory_hostname}}`)",
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/config:/config:rw"
      - "/mnt/extdrv01/apps/media-content:/data01:ro"
      - "/mnt/extdrv02/apps/media-content:/data02:ro"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete