---
- set_fact:
    appname: wireguard-client

- name: provision infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-provision

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"
    env:
      PUID: "{{ appconfig[appname].exec_as_user }}"
      PGID: "{{ appconfig[appname].exec_as_group }}"
      TZ: "Europe/Paris"
    labels: |
      {
        "traefik.enable": "false",
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/config/sensitive:/config/wg_confs"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    capabilities:
      - NET_ADMIN
- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete

- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete