---
- set_fact:
    appname: tempo

- name: provision infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-provision

- name: Template {{appname}} config
  when:  appconfig[appname].appstate == 'started'
  become: true
  ansible.builtin.template:
    src: templates/{{appname}}/config/tempo.template.j2
    dest: "{{ appconfig[appname].config_folder }}/tempo.yaml"
    owner: "{{ appconfig[appname].exec_as_user }}"
    group: "{{ appconfig[appname].exec_as_group }}"
    mode: '0644'

- name: "Manage {{appname}} container state"
  docker_container:
    name: "{{appname}}"
    hostname: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "{{ appconfig[appname].exec_as_user }}:{{ appconfig[appname].exec_as_group }}"
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"
    command: -config.file=/etc/tempo.yaml
    env:
    labels: |
      {
        "traefik.enable": "true",
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "3200",
        "traefik.http.services.{{appname}}.loadbalancer.server.scheme": "http",
        "traefik.http.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.routers.{{appname}}.rule": "Host(`{{appname}}.{{inventory_hostname}}`)",
      }
    volumes:
      - "{{ appconfig[appname].data_folder }}:/var/tempo:rw"
      - "{{ appconfig[appname].config_folder }}/tempo.yaml:/etc/tempo.yaml:ro"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if {{appname}} server is up
  when:  appconfig[appname].appstate == 'started'
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/ready"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2
  delegate_to: 127.0.0.1

- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete