---
- set_fact:
    appname: grafana-agent-flow


- name: provision infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-provision

- name: "Read a dev tenant admin token content"
  shell: |
    cat /home/{{ansible_user}}/apps/mimir/data/dev_admin.token
  register: mdev_admin_token
  when: appconfig[appname].appstate == 'started'

- name: "Read a dev tenant admin token content"
  shell: |
    cat /home/{{ansible_user}}/apps/loki/data/dev_admin.token
  register: ldev_admin_token
  when: appconfig[appname].appstate == 'started'

- name: "Read a dev tenant admin token content"
  shell: |
    cat /home/{{ansible_user}}/apps/tempo/data/dev_admin.token
  register: tdev_admin_token
  when: appconfig[appname].appstate == 'started'

- name: Template {{appname}} config
  when:  appconfig[appname].appstate == 'started'
  become: true
  ansible.builtin.template:
    src: templates/{{appname}}/config/agent.template.j2
    dest: "{{ appconfig[appname].config_folder }}/agent.yml"
    owner: "{{ appconfig[appname].exec_as_user }}"
    group: "{{ appconfig[appname].exec_as_group }}"
    mode: '0644'


- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    hostname: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "{{ appconfig[appname].exec_as_user }}:{{ appconfig[appname].exec_as_group }}"
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"
    command: -config.file=/etc/agent/agent.yml -server.http.address=0.0.0.0:80  -enable-features=integrations-next -config.enable-read-api
    env:
    labels: |
      {
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "80",
        "traefik.http.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.routers.{{appname}}.rule": "Host(`{{appname}}.{{inventory_hostname}}`)",


        "traefik.http.services.{{appname}}-front-end-receiver.loadbalancer.server.port": "12347",
        "traefik.http.routers.{{appname}}-front-end-receiver.service": "{{appname}}-front-end-receiver",
        "traefik.http.routers.{{appname}}-front-end-receiver.entrypoints": "http",
        "traefik.http.routers.{{appname}}-front-end-receiver.tls": "false",
        "traefik.http.routers.{{appname}}-front-end-receiver.rule": "Host(`{{appname}}-front-end-receiver.{{inventory_hostname}}`)",

        "traefik.http.services.{{appname}}-grpc-otlp-traces.loadbalancer.server.port": "4317",
        "traefik.http.services.{{appname}}-grpc-otlp-traces.loadbalancer.server.scheme": "h2c",
        "traefik.http.routers.{{appname}}-grpc-otlp-traces.service": "{{appname}}-grpc-otlp-traces",
        "traefik.http.routers.{{appname}}-grpc-otlp-traces.entrypoints": "https",
        "traefik.http.routers.{{appname}}-grpc-otlp-traces.tls": "true",
        "traefik.http.routers.{{appname}}-grpc-otlp-traces.rule": "Host(`{{appname}}-grpc-otlp-traces.{{inventory_hostname}}`)",
      }
    volumes:
      - /home/{{ ansible_user }}/apps/{{appname}}/config/agent.yml:/etc/agent/agent.yml:ro
      - /home/{{ ansible_user }}/apps/{{appname}}/data:/data:rw
      # - /home/{{ansible_user}}/apps/tls/{{inventory_hostname}}-root-ca.pem:/tls/root-ca.pem:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if server is up {{inventory_hostname}}
  when:  appconfig[appname].appstate == 'started'
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/-/ready"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2

- name: delete infra
  ansible.builtin.include_role:
    name: docker_lab
    tasks_from: infra-delete