admin_client:
  storage:
    s3:
      bucket_name: enterprise-logs-admin
auth:
  type: enterprise
auth_enabled: true
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 256
      parallelism: 10
    memcached_client:
      # host: infra:11211
      addresses: dns+infra:11211
  write_dedupe_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      addresses: dns+infra:11212
cluster_name: enterprise-logs
common:
  compactor_address: http://infra:4100
  compactor_grpc_address: infra:4095
  path_prefix: /var/lib/enterprise-logs
  replication_factor: 3
  storage:
    s3:
      access_key_id: admin
      bucketnames: enterprise-logs-chunks
      endpoint: infra:9000
      insecure: true
      s3forcepathstyle: true
      secret_access_key: password
compactor:
  compaction_interval: 10m
  delete_batch_size: 70
  delete_max_interval: 0s
  delete_request_cancel_period: 24h
  deletion_mode: filter-and-delete
  retention_delete_delay: 1h
  retention_delete_worker_count: 150
  retention_enabled: true
  retention_table_timeout: 0s
ingester:
  max_chunk_age: 2h
license:
  path: /etc/enterprise-logs/license.jwt
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 6
  ingestion_rate_mb: 4
  max_cache_freshness_per_query: 10m
  max_chunks_per_query: 2000000
  max_line_size: 0
  max_line_size_truncate: false
  max_query_parallelism: 32
  max_query_series: 500
  reject_old_samples: true
  reject_old_samples_max_age: 1w
  retention_period: 31d
  retention_stream: []
  split_queries_by_interval: 15m
  unordered_writes: true
memberlist:
  join_members:
  - infra:4946
querier:
  max_concurrent: 15
  query_ingesters_within: 15m
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      default_validity: 12h
      memcached_client:
        addresses: dns+infra:11213
        timeout: 500ms
ruler:
  alertmanager_client:
    # basic_auth_password: TOKEN
    # basic_auth_username: TENANTID
  alertmanager_url: http://infra:9093
  enable_api: true
  evaluation_interval: 1m
  poll_interval: 1m
  remote_write:
    clients:
      prom:
        # basic_auth:
        #   password: TOKEN
        #   username: TENANTID
        headers: {}
        remote_timeout: 30s
        tls_config:
          insecure_skip_verify: true
        url: http://infra:9090/api/v1/write
        write_relabel_configs:
        - action: replace
          replacement: enterprise-logs
          target_label: cluster
    config_refresh_period: 10s
    enabled: true
  storage:
    s3:
      access_key_id: admin
      bucketnames: enterprise-logs-ruler
      endpoint: infra:9000
      insecure: true
      s3forcepathstyle: true
      secret_access_key: password
    type: s3
runtime_config:
  file: /etc/enterprise-logs/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2023-01-01"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: tsdb
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
  http_server_read_timeout: 5m
  http_server_write_timeout: 5m
  log_level: info
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      addresses: dns+infra:11214
table_manager:
  retention_deletes_enabled: false
  retention_period: 0