
- name: Install GEL
  hosts:
    - write
    - read
  tasks:
    - name: install GEL license
      copy:
        src: templates/sensitive/gel-license.jwt
        dest: /etc/enterprise-logs/license.jwt

    - name: configure GEL
      copy:
        src: templates/gel-config.yml
        dest: /etc/enterprise-logs/config.yaml


    - name: configure GEL runtime
      copy:
        src: templates/runtime-config.yaml
        dest: /etc/enterprise-logs/runtime-config/runtime-config.yaml


- name: Install GEL write path
  hosts:
    - write
  tasks:
    - name: create the enterprise-logs service file
      copy:
        src: templates/enterprise-logs-write.service
        dest: /etc/systemd/system/enterprise-logs-write.service
    - name: reload systemd
      systemd:
        daemon_reload: yes
    - name: restart enterprise-logs-write
      systemd:
        name: enterprise-logs-write
        state: restarted

- name: Install GEL write read
  hosts:
    - read
  tasks:
    - name: create the enterprise-logs service file
      copy:
        src: templates/enterprise-logs-read.service
        dest: /etc/systemd/system/enterprise-logs-read.service
    - name: reload systemd
      systemd:
        daemon_reload: yes
    - name: restart enterprise-logs-read
      systemd:
        name: enterprise-logs-read
        state: restarted


- name: Check readiness on readpath
  hosts:
    - infra
  tasks:
    - name: Check if server is up 
      uri:
        url: "http://{{ item }}:3100/ready"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 100
      delay: 2
      loop: "{{ query('inventory_hostnames', 'write') }}"

- name: Check readiness on readpath
  hosts:
    - infra
  tasks:
    - name: Check if server is up 
      uri:
        url: "http://{{ item }}:3100/ready"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 100
      delay: 2
      loop: "{{ query('inventory_hostnames', 'read') }}"

- name: Gnerate token
  hosts:
    - write01
  tasks:
    - name: check if GEL is present
      stat:
        path: /root/gel-admin-token.txt
      register: stat_token
    - name: run the tokengen job
      command: /usr/local/bin/enterprise-logs --config.file=/etc/enterprise-logs/config.yaml --target=tokengen --tokengen.token-file=/root/gel-admin-token.txt
      args:
        creates: /root/gel-admin-token.txt
      when: not stat_token.stat.exists