---
- name: download kubeconfig to local machine
  fetch:
    src: /home/cloud-user/.kube/config
    dest: "~/.kube/config"
    flat: true

# - name: merge config files locally
#   shell: |
#     cp ~/.kube/config ~/.kube/config.bak && KUBECONFIG=~/.kube/config:/tmp/{{ ansible_hostname }}_kubeconfig kubectl config view --flatten > /tmp/config && mv /tmp/config ~/.kube/config
#   delegate_to: localhost
