---
- name: Prepare Hosts
  hosts:
    - all
  vars:
    aptcacherproxy: http://work.lan:3142/
  vars_files:
  tasks:
    - name: apt cacher on host machine
      when: aptcacherproxy is defined
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/proxy
        regexp: '.*Acquire::http.*'
        line: Acquire::http { Proxy "{{ aptcacherproxy }}"; }
        create: true

    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: full

    - name: Reboot
      reboot:
        reboot_timeout: 30

