---
- name: start-services
  hosts:
    - selected
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
    - ../vars/sensitive/secretappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        # platform essentials
        - traefik
        - portainer

        # artifact repositories
        - registry
        - regui
        - reposilite

        # identity
        - keycloak

        # databases
        - oracledb
        - mysql
        - mariadb
        - postgres
        - adminer

        #storage
        - minio

        # messaging
        - kafka
        - artemis

        # observability
        - node-exporter
        - promgcloud
        - memcached
        - cadvisor
        - prometheus
        - mimir
        - loki
        - tempo
        - grafana-enterprise
        - grafana
        - grafana-agent
        - grafana-agent-flow

        # functional apps
        - smoke-test-app
      loop_control:
        loop_var: rolesvar
