---
- name: start-services
  hosts:
    - selected
  vars:
    global_recreate: false
    global_appstate: stopped
    global_purge: false
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
    - ../vars/sensitive/secretappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        # platform essentials
        # - traefik
        # - portainer
        # - registry
        # - regui
        # - keycloak
        # - reposilite
        # - cadvisor

        # databases
        - postgres
        - mariadb
        - oracledb
        - minio
        - memcached
        - adminer

        # messaging
        - kafka
        - artemis

        # observability
        - prometheus
        - grafana
        - grafana-enterprise
        - grafana-alpha
        - loki
        - mimir
        - grafana-agent
        - tempo


        # functional apps
        - smoke-test-app
        - shopping-cart
        - products
        - web-shop
      loop_control:
        loop_var: rolesvar
