---
- name: start-services
  hosts:
    - selected
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
    - ../vars/sensitive/secretappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        # platform essentials
        - traefik
        - portainer

        - prometheus
        - loki
        - tempo
        - postgres
        - keycloak
        - grafana-enterprise

      loop_control:
        loop_var: rolesvar
