---
- name: start-services
  hosts:
    - selected
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
    - ../vars/sensitive/secretappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        # platform essentials
        - traefik
        - portainer
        - registry
        - regui
        - keycloak
        - reposilite

        # # databases
        - postgres
        - mariadb
        # - oracledb
        - minio
        # - memcached
        # - adminer

        # # messaging
        # - kafka
        # - artemis

        # # observability
        # - cadvisor
        - mimir
        - loki
        - tempo
        - prometheus
        - grafana-agent
        # - grafana
        - grafana-enterprise
        # - grafana-alpha


        # # functional apps
        - smoke-test-app
        # - shopping-cart
        # - products
        # - web-shop
      loop_control:
        loop_var: rolesvar
