---
baremetal:
  hosts:
    zez.duckdns.org:
      ansible_connection: ssh
      ansible_user: apham
      ansible_python_interpreter: /usr/bin/python3
      arch: linux-amd64
vms:
  hosts:
    vrbx.duckdns.org:
      ansible_connection: ssh
      ansible_user: cloud-user
      ansible_python_interpreter: /usr/bin/python3
      arch: linux-amd64
    demvm.duckdns.org:
      ansible_connection: ssh
      ansible_user: alain_pham_grafana_com
      ansible_python_interpreter: /usr/bin/python3
      arch: linux-amd64


selected:
  # children:
  #   x86:
  #   vms:
  hosts:
    zez.duckdns.org: