---
# ################################################################################################
# # Networking
# ################################################################################################

- name: mvp networking
  hosts:
    - awon.cpss.duckdns.org
    - bbee.cpss.duckdns.org
    - cipi.pssy.duckdns.org
    - arev.pssy.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - traefik
        - portainer
      loop_control:
        loop_var: rolesvar

# ################################################################################################
# # DevOps tools
# ################################################################################################

- name: awon devops utils
  hosts:
    - awon.cpss.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - registry
        - regui
        - reposilite
        - static
        - acng
      loop_control:
        loop_var: rolesvar

# ################################################################################################
# # Home Lab Services on awon
# ################################################################################################

- name: awon homelab services
  hosts:
    - awon.cpss.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/homelabappconfig.yml
  tasks:
    - include_role:
        name: home_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        # - plex
        - jellyfin
        - teddycast
        - rentman
        - wireguard-client
        - transmission
        - pkdex
        - homeassistant
        - syncthing
        # - nextcloud
        # - bazarr
        # - radarr
      loop_control:
        loop_var: rolesvar

# ################################################################################################
# # Middleware infra on awon
# ################################################################################################

- name: awon homelab services
  hosts:
    - awon.cpss.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - artemis
      loop_control:
        loop_var: rolesvar

# ################################################################################################
# # Home Lab Services on bbee
# ################################################################################################

- name: bbee homelab services
  hosts:
    - bbee.cpss.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/homelabappconfig.yml
  tasks:
    - include_role:
        name: home_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - pkdex
      loop_control:
        loop_var: rolesvar

- name: rpi specific glcoud
  hosts:
    - bbee.cpss.duckdns.org
    - cipi.pssy.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/dockerappconfig.yml
    - ../vars/sensitive/secretappconfig.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - node-exporter
        - promgcloud
      loop_control:
        loop_var: rolesvar
