---
- name: build java bytecode on x86 machines
  hosts:
    - awon.cpss.duckdns.org
  serial: 1
  vars_files:
    - ../vars/appcicd.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: cicd-java-build
      loop:
        - smoke-test-app
      loop_control:
        loop_var: rolesvar

- name: build & push containers to registry
  hosts:
    - awon.cpss.duckdns.org
    - bbee.cpss.duckdns.org
  vars_files:
    - ../vars/appcicd.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: cicd-container-push
      loop:
        - smoke-test-app
      loop_control:
        loop_var: rolesvar

- name: push multi arch manifest
  hosts:
    - awon.cpss.duckdns.org
  vars_files:
    - ../vars/appcicd.yml
  tasks:
    - include_role:
        name: docker_lab
        tasks_from: cicd-container-manifest
      loop:
        - smoke-test-app
      loop_control:
        loop_var: rolesvar
