---


- name: awon homelab services
  hosts:
    - awon.cpss.duckdns.org
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  vars_files:
    - ../vars/global.yml
    - ../vars/images.yml
    - ../vars/homelabappconfig.yml
  tasks:
    - include_role:
        name: home_lab
        tasks_from: app-{{ rolesvar }}
      loop:
        - transmission
      loop_control:
        loop_var: rolesvar
